default_url_options:
  host: 'graduation-project-msmn.onrender.com'  # Renderのドメイン
  protocol: 'https'

mailer:
  from: 'dev-noreply@yourapp.com'
GMAIL_ADDRESS: 'm56998673@gmail.com'
GMAIL_PASSWORD: 'zstcispdgoyiyabx'
RAILS_MASTER_KEY: '9138dc8c5919dfc0f5a2428782ef820d'